### ISSUE TITLE
unable to start kibana service version 4.2.0 - Unit kibana.service entered failed state.

### ISSUE THREAD

**Issue by ltutar** [jlambert121/jlambert121-kibana#58]
I have the following yaml:
kibana::version: '4.2.0'

The kibana service will not start and there is no kibana logging.
I can install 4.1.2 without any problems.

[root@elkagent config]# service kibana status
Redirecting to /bin/systemctl status  kibana.service
kibana.service - Kibana service
   Loaded: loaded (/usr/lib/systemd/system/kibana.service; enabled)
   Active: failed (Result: exit-code) since Tue 2015-11-03 13:39:11 CET; 3s ago
  Process: 5720 ExecStart=/opt/kibana/bin/kibana (code=exited, status=1/FAILURE)
 Main PID: 5720 (code=exited, status=1/FAILURE)

Nov 03 13:39:11 elkagent.home kibana[5720]: at Error (native)
Nov 03 13:39:11 elkagent.home kibana[5720]: at Object.fs.openSync (fs.js:500:18)
Nov 03 13:39:11 elkagent.home kibana[5720]: at Object.fs.writeFileSync (fs.js:1099:15)
Nov 03 13:39:11 elkagent.home kibana[5720]: at save (/opt/kibana-4.2.0-linux-x64/node_modules/babel-core/lib/api/register/cache.js:35:19)
Nov 03 13:39:11 elkagent.home kibana[5720]: at process._tickDomainCallback (node.js:381:11)
Nov 03 13:39:11 elkagent.home kibana[5720]: at Function.Module.runMain (module.js:503:11)
Nov 03 13:39:11 elkagent.home kibana[5720]: at startup (node.js:129:16)
Nov 03 13:39:11 elkagent.home kibana[5720]: at node.js:814:3
Nov 03 13:39:11 elkagent.home systemd[1]: kibana.service: main process exited, code=exited, status=1/FAILURE
Nov 03 13:39:11 elkagent.home systemd[1]: Unit kibana.service entered failed state.
[root@elkagent config]# service kibana status
Redirecting to /bin/systemctl status  kibana.service
kibana.service - Kibana service
   Loaded: loaded (/usr/lib/systemd/system/kibana.service; enabled)
   Active: failed (Result: exit-code) since Tue 2015-11-03 13:39:11 CET; 19s ago
  Process: 5720 ExecStart=/opt/kibana/bin/kibana (code=exited, status=1/FAILURE)
 Main PID: 5720 (code=exited, status=1/FAILURE)

Nov 03 13:39:11 elkagent.home kibana[5720]: at Error (native)
Nov 03 13:39:11 elkagent.home kibana[5720]: at Object.fs.openSync (fs.js:500:18)
Nov 03 13:39:11 elkagent.home kibana[5720]: at Object.fs.writeFileSync (fs.js:1099:15)
Nov 03 13:39:11 elkagent.home kibana[5720]: at save (/opt/kibana-4.2.0-linux-x64/node_modules/babel-core/lib/api/register/cache.js:35:19)
Nov 03 13:39:11 elkagent.home kibana[5720]: at process._tickDomainCallback (node.js:381:11)
Nov 03 13:39:11 elkagent.home kibana[5720]: at Function.Module.runMain (module.js:503:11)
Nov 03 13:39:11 elkagent.home kibana[5720]: at startup (node.js:129:16)
Nov 03 13:39:11 elkagent.home kibana[5720]: at node.js:814:3
Nov 03 13:39:11 elkagent.home systemd[1]: kibana.service: main process exited, code=exited, status=1/FAILURE
Nov 03 13:39:11 elkagent.home systemd[1]: Unit kibana.service entered failed state.
[root@elkagent config]# cd /var/log/kibana/
[root@elkagent kibana]# ls -al
total 4
drwxr-xr-x.  2 kibana kibana    6 Nov  3 13:36 .
drwxr-xr-x. 11 root   root   4096 Nov  3 13:36 ..
[root@elkagent kibana]# cd /opt/kibana
[root@elkagent kibana]# ls
bin  config  installedPlugins  LICENSE.txt  node  node_modules  optimize  package.json  README.txt  src  webpackShims
[root@elkagent kibana]# cd bin
[root@elkagent bin]# ls
kibana  kibana.bat
[root@elkagent bin]# ./kibana --version
4.2.0
[root@elkagent bin]#

**Comment by jlambert121** [comment]
I don't have an environment to test 4.2.0 right now, if you could narrow down the issue and submit a PR that would be wonderful.

**Comment by philipwigg** [comment]
May be related? https://github.com/elastic/kibana/issues/5237

**Comment by ltutar** [comment]
I am sticking to 4.1.2 at this moment to keep progress with the other modules.

**Comment by jlambert121** [comment]
#67 fixes some systemd issues as well, but I'm not sure that was the issue behind this one.  Does master + kibana 4.3.0 resolve issues for you?

**Comment by ltutar** [comment]
with tag 2.5.0, I am able to install kibana version 2.5.0. I will close the issue.
